### ISSUE TITLE
Ethernet / IntelMausiEthernet while updating to 10.15.4 (or 5)

### ISSUE THREAD

**Issue by Skadi8** [cmer/gigabyte-z390-aorus-master-hackintosh#68] opened 2020-05-31 00:36 UTC
Hi there,

First of all, a big THANKS for this repo - I have consistently used it on my Hackintosh and It has just worked fine for nearly 6 months. 
Almost same build - Aorus Master, i9 9900k, 5700 XT for me. 

Sorry to bug you like this, but I have a big issue, just spent hours trying to find a solution or a fix on the internet and on my own but cannot get through it. 

I used your Clover tutorial fine for a while. 
Then recently I updated to 10.15.5 (I was running 10.15.3), via Clover. I had a few issues with the update but it eventually completed. 

I realized that on the updated system, the internet was off. No internet, and actually no NIC recognized in System Reports. 

I went back to your guide and figured this would actually be a good time to upgrade to OpenCore, that it would solve the problem. 

I formatted everything, EFI included, for the best and cleanest conversion - VRAM resetted and cleaned a few times. 

I successfully installed to 10.15.5 again via OpenCore. And... same. In System Reports, no ethernet card shows up. So of course no ethernet or internet whatsoever, same in Utilities on the bootable USB itself of course. Does the same whether on Time Machine recovery or clean install. 

I tried to run kextstat | grep -v com.apple on Terminal, and every other kext is running, but not Intel Mausi Ethernet. I tried yours and the one from the official repo, nothing. 

I am running out of ideas, would you have a clue ?

**Comment by Skadi8** [comment] 2020-05-31 01:01
I just got the hang of it. Leaving this for people who might be in my case and letting you close it, as admin of this repo. 

IT WORKED with Intel Mausi, not Intel Mausi Ethernet. The other Kext.

**Comment by EvSpirit** [comment] 2020-06-01 10:34
I faced the same problem recently. It seems the problem is caused by Mausi version update from 2.5.0 to 2.5.1b1. I managed to fix it by reverting one to 2.5.0 and that's it.

**Comment by riley21** [comment] 2020-06-06 05:07
@EvSpirit fix worked for me too.

**Comment by luangjokaj** [comment] 2020-06-20 03:01
> I just got the hang of it. Leaving this for people who might be in my case and letting you close it, as admin of this repo. 
> 
> 
> 
> IT WORKED with Intel Mausi, not Intel Mausi Ethernet. The other Kext. 
> 
> 
> 
> Thank you again so much for all ressources here. Very helpful!
> 
> 

I downloaded the latest Kext for Intel Mausi, renamed it in the config with the original name, and works. Thank you for the tip.

**Comment by nearlynogravitas** [comment] 2020-07-01 00:31
I have [a branch](https://github.com/nearlynogravitas/gigabyte-z390-aorus-master-hackintosh/commit/f10e8999248a621742bcc50f672fd1250374a4d3) with a downgraded version of the kext that seems to work.  @cmer, would you be open to a pull request for this?  Does the ethernet kext in your repository work for you?  Thanks

**Comment by cmer** [comment] 2020-07-01 01:27
Interesting. Thanks guys for all the work on this. 

I use a 10gbps nic so it’s entirely possible that my mobo nic doesn’t work either and that I never noticed. 

Yes I’ll merge that pull request. It seems like a few of you have been able to reproduce and fix the issue by reverting to an older version.

**Comment by nearlynogravitas** [comment] 2020-07-01 01:37
Thanks.  I posted the pull request

**Comment by cmer** [comment] 2020-07-01 01:47
Fixed in #72

**Closed by cmer** 2020-07-01 01:47 UTC
